// <auto-generated />
using System;
using MakiseSharpServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MakiseSharpServer.API.Migrations
{
    [DbContext(typeof(MakiseDbContext))]
    [Migration("20190217155841_RemoveAppRefreshTokens")]
    partial class RemoveAppRefreshTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0-preview.19074.3");

            modelBuilder.Entity("MakiseSharpServer.Domain.Entities.UserAggregate.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DiscordAccessToken")
                        .IsRequired();

                    b.Property<ulong>("DiscordId");

                    b.Property<string>("DiscordRefreshToken")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("DiscordId")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
